version: '3.8'

services:
  avara-dev-db:
    image: postgres:latest
    container_name: avara-dev-db
    environment:
      POSTGRES_USER: avara_dev_db
      POSTGRES_PASSWORD: 4784961Edc!
      POSTGRES_DB: avara_dev_db
    ports:
      - "5445:5432"
    volumes:
      - avara-dev-db:/var/lib/postgresql/data
    networks:
      - avara-network

  core-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && pnpm start:prod"
    env_file:
      - ./api/.env.production
    depends_on:
      - avara-dev-db
    ports:
      - "3002:3000"
    networks:
      - avara-network
    volumes:
      - uploads-data:/usr/src/app/uploads
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./admin/.env.production
    ports:
      - "3003:3000"
    networks:
      - avara-network
    depends_on:
      - core-api

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

volumes:
  minio_data:
  minio_config:
  avara-dev-db:
  uploads-data:
    driver: local

networks:
  avara-network:
    driver: bridge
