import { Field, InputType } from '@nestjs/graphql'
import GraphQLJSON from 'graphql-type-json'

@InputType()
export class UpsertTranslationInput {
  @Field(() => String)
  locale: string

  @Field(() => String)
  entityType: string

  @Field(() => String)
  entityId: string

  @Field(() => GraphQLJSON)
  fields: Record<string, string>

  @Field(() => Boolean)
  autoGenerated: boolean
}
