import { Field, InputType } from '@nestjs/graphql'
import GraphQLJSON from 'graphql-type-json'
import { TranslationProvider } from './enum'

@InputType()
export class UpsertTranslationInput {
  @Field(() => String)
  locale: string

  @Field(() => String)
  entityType: string

  @Field(() => String)
  entityId: string

  @Field(() => GraphQLJSON)
  fields: Record<string, string>

  @Field(() => Boolean)
  autoGenerated: boolean

  @Field(() => TranslationProvider)
  translationProvider: TranslationProvider

  @Field(() => Date)
  lastSyncedAt: Date
}
