import { Field, ID, ObjectType } from '@nestjs/graphql'
import GraphQLJSON from 'graphql-type-json'

@ObjectType()
export class Translation {
  @Field(() => ID)
  id: string

  @Field(() => String)
  entityType: string

  @Field(() => String)
  entityId: string

  @Field(() => String)
  locale: string

  @Field(() => String)
  fieldName: string

  @Field(() => String, { nullable: true })
  translatedValue: string | null

  @Field(() => Date, { nullable: true })
  lastSyncedAt: Date | null

  @Field(() => Boolean)
  autoGenerated: boolean
}

@ObjectType()
export class TranslationResponse {
  @Field(() => GraphQLJSON)
  fields: Record<string, string>
}

@ObjectType()
export class TranslationResponseArray {
  @Field(() => [GraphQLJSON])
  items: Record<string, string>[]
}
