export const errorCodes = {
  LOGIN_FAILED: 'LOGIN_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
  NO_SESSION: 'NO_SESSION',
  REFRESH_FAILED: 'REFRESH_FAILED',
}
