import { Field, ObjectType, InputType, ID } from '@nestjs/graphql'
import { FacetValue } from './facet-value.types'
import {
  CreateSeoMetadataInput,
  SeoMetadata,
  UpdateSeoMetadataInput,
} from '@av/seo/api/types/seo-metadata.types'

@ObjectType()
export class Asset {
  @Field(() => ID)
  id: string

  @Field()
  name: string

  @Field()
  originalName: string

  @Field()
  preview: string

  @Field()
  type: string

  @Field()
  source: string

  @Field()
  autoGenerated: string
}

@ObjectType()
export class Product {
  @Field(() => ID)
  id: string

  @Field()
  name: string

  @Field()
  slug: string

  @Field()
  isPrivate: boolean

  @Field()
  autoGenerated: boolean

  @Field({ nullable: true })
  description?: string

  @Field(() => [FacetValue], { nullable: true })
  facetValues?: FacetValue[]

  @Field(() => String, { nullable: true })
  featuredAssetId?: string

  @Field(() => Asset, { nullable: true })
  featuredAsset?: Asset

  @Field(() => [Asset], { nullable: true })
  documents?: Asset[]

  @Field(() => SeoMetadata, { nullable: true })
  seoMetadata?: SeoMetadata

  @Field()
  createdAt: Date

  @Field()
  updatedAt: Date

  @Field({ nullable: true })
  createdBy: string

  @Field({ nullable: true })
  updatedBy?: string
}

@InputType()
export class CreateProductInput {
  @Field()
  name: string

  @Field()
  slug: string

  @Field({ nullable: true })
  isPrivate?: boolean

  @Field({ nullable: true })
  autoGenerated?: boolean

  @Field({ nullable: true })
  description?: string

  @Field(() => [String], { nullable: true })
  facetValueIds?: string[]

  @Field(() => String, { nullable: true })
  featuredAssetId?: string

  @Field(() => [String], { nullable: true })
  documentIds?: string[]

  @Field(() => CreateSeoMetadataInput, { nullable: true })
  seoMetadata?: CreateSeoMetadataInput

  facetValues?: any
}

@InputType()
export class UpdateProductInput {
  @Field({ nullable: true })
  name?: string

  @Field({ nullable: true })
  slug?: string

  @Field({ nullable: true })
  autoGenerated?: boolean

  @Field({ nullable: true })
  description?: string

  @Field({ nullable: true })
  isPrivate?: boolean

  @Field(() => [String], { nullable: true })
  facetValueIds?: string[]

  @Field(() => String, { nullable: true })
  featuredAssetId?: string

  @Field(() => [String], { nullable: true })
  documentIds?: string[]

  @Field(() => UpdateSeoMetadataInput, { nullable: true })
  seoMetadata?: UpdateSeoMetadataInput
}
